version: '3.8'

services:
  app:
    build: .
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    environment:
      - PYTHONPATH=/workspace/apps/api
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
      - "5432:5432"
      - "6379:6379"
    working_dir: /workspace
    tty: true
    stdin_open: true
