"""add notifications relationship to customer model

Revision ID: 9039b0cba195
Revises: 501db6a3e7b2
Create Date: 2025-09-03 03:09:22.413356

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "9039b0cba195"
down_revision: Union[str, Sequence[str], None] = "501db6a3e7b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
